#apiVersion: admissionregistration.k8s.io/v1beta1
#kind: MutatingWebhookConfiguration
#metadata:
#  name: mutating-webhook-configuration
#webhooks:
#  - name: mutation.gatekeeper.sh
#    timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - name: validation.gatekeeper.sh
    sideEffects: None
    timeoutSeconds: 5
    namespaceSelector:
      matchExpressions:
        - key: admission.gatekeeper.sh/ignore
          operator: DoesNotExist
  - name: check-ignore-label.gatekeeper.sh
    sideEffects: None
    timeoutSeconds: 5
