# permissions for end users to edit constraintpodstatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: constraintpodstatus-editor-role
rules:
- apiGroups:
  - status.gatekeeper.sh
  resources:
  - constraintpodstatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - status.gatekeeper.sh
  resources:
  - constraintpodstatuses/status
  verbs:
  - get
