# permissions for end users to view constraintpodstatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: constraintpodstatus-viewer-role
rules:
- apiGroups:
  - status.gatekeeper.sh
  resources:
  - constraintpodstatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - status.gatekeeper.sh
  resources:
  - constraintpodstatuses/status
  verbs:
  - get
