# permissions for end users to view constrainttemplatepodstatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: constrainttemplatepodstatus-viewer-role
rules:
- apiGroups:
  - status.gatekeeper.sh
  resources:
  - constrainttemplatepodstatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - status.gatekeeper.sh
  resources:
  - constrainttemplatepodstatuses/status
  verbs:
  - get
