apiVersion: v1
kind: Pod
metadata:
  name: opa
  namespace: bad-prod-ns
spec:
  containers:
    - name: opa
      image: openpolicyagent/opa:0.9.2
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
