# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/config.gatekeeper.sh_configs.yaml
- bases/status.gatekeeper.sh_constraintpodstatuses.yaml
- bases/status.gatekeeper.sh_constrainttemplatepodstatuses.yaml
# +kubebuilder:scaffold:crdkustomizeresource

bases:
- ../../vendor/github.com/open-policy-agent/frameworks/constraint/deploy


patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_configs.yaml
#- patches/webhook_in_constraintpodstatuses.yaml
#- patches/webhook_in_constrainttemplatepodstatuses.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_configs.yaml
#- patches/cainjection_in_constraintpodstatuses.yaml
#- patches/cainjection_in_constrainttemplatepodstatuses.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
