apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-host2
spec:
  rules:
  - host: example-host.example.com
    http:
      paths:
      - backend:
          serviceName: nginx3
          servicePort: 80
