replicas: 3
auditInterval: 60
constraintViolationsLimit: 20
auditFromCache: false
disableValidatingWebhook: false
auditChunkSize: 0
logLevel: INFO
emitAdmissionEvents: false
emitAuditEvents: false
image:
  repository: openpolicyagent/gatekeeper
  release: v3.1.0-rc.1
  pullPolicy: IfNotPresent
nodeSelector: { kubernetes.io/os: linux }
affinity: {}
tolerations: []
podAnnotations:
  { container.seccomp.security.alpha.kubernetes.io/manager: runtime/default }
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
